---
- hosts: ubuntu
  pre_tasks:
    - import_tasks: tasks/python.yml
  tasks:
    - name: load variables
      include_vars: config/variables.yml
    - import_tasks: tasks/bash.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/nodejs.yml
    - import_tasks: tasks/maven.yml
    - import_tasks: tasks/aws.yml
