---
- hosts: ubuntu
  pre_tasks:
    - include: tasks/python.yml
  tasks:
    - name: load variables
      include_vars: config/variables.yml
    - include: tasks/bash.yml
    - include: tasks/vim.yml
    - include: tasks/git.yml
    - include: tasks/docker.yml
    - include: tasks/nodejs.yml
    - include: tasks/aws.yml
