- name: install AWS CLI
  pip:
    name: awscli
    extra_args: --upgrade --user
- name: mkdir ~/.aws
  file:
    path: ~/.aws
    state: directory
- name: copy file to ~/.aws/credentials
  copy:
    src: config/files/.aws_credentials
    dest: ~/.aws/credentials
- name: copy file to ~/.aws/config
  copy:
    src: config/files/.aws_config
    dest: ~/.aws/config
