- name: provision ~/.bash_aliases
  file:
    path: ~/.bash_aliases
    state: touch
- name: add cdhome to ~/.bash_aliases
  lineinfile:
    path: ~/.bash_aliases
    regexp: '^alias cdhome='
    line: "alias cdhome='cd {{ cdhome_dir }}'"
- name: run cdhome in ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    regexp: '^cdhome'
    line: 'cdhome'
